name: medicine_application
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
workspace:
  - packages/ui

environment:
  sdk: ^3.10.0-49.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  bloc_concurrency: ^0.3.0
  google_sign_in: ^7.1.1
  auto_route: ^10.1.0
  flutter_secure_storage: ^9.2.4
  dio: ^5.9.0
  logger: ^2.6.1
  web_socket_channel: ^3.0.3
  rxdart: ^0.28.0

  ui:
    path: packages/ui
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
